### ISSUE TITLE
Found problem with backslashes parsing

### ISSUE THREAD

**Issue by seregvan** [StefH/System.Linq.Dynamic.Core#307]
You closed my previous issue as a question so I'm opening a new one.
I think I found the problem in your parsing. I can't see the reason to do this in string literal parsing except the case when I try to find " in the result.

``` c#
if (next == '"')
{
     NextChar();
}
```

Because if I use query `"contains(\"\\\")"` it fails with unterminated literal, but if I change query to `"contains(\"\\a\")"` it works finding "\\a" string. And also if I use `"contains(\"\\\\\")"` it works with string "\\\\" (string with two real slashes). 

So I think the correct solution will be to remove this if statement and just replace `\"` to `"` in the result token if it was a string literal. In this case if user will want to put " in query string it should be escaped inside this string. At least it will not break any existing code. 
The better approach will be (in my opinion) to escape all the characters in the string by user and to unescape by parser. That means `\\\\` will evaluate to `\` and not to `\\`.
I understand your workaround by using `@0` but it's not the case when search string comes outside my app.

**Comment by alexweav** [comment]
Hello @StefH, I just ran into this issue as well. The filter `foo = "\"asdf\""` seems to match the literal including backslashes, and the filter `foo = """asdf"""`, which is the literal format documented on the wiki, causes a parse failure.

Are there any workaround for parsing a dynamic linq lambda which contains a quote, other than substitutions? If not, would you please be able to point me towards this area in the code? I might be able to provide a PR, with some guidance.

**Comment by StefH** [comment]
@alexweav The parsing code is located here: 
- https://github.com/StefH/System.Linq.Dynamic.Core/blob/master/src/System.Linq.Dynamic.Core/Tokenizer/TextParser.cs#L274
- https://github.com/StefH/System.Linq.Dynamic.Core/blob/8d8ecf9c2340f4518dc377e9fe7a6767dd71e392/src/System.Linq.Dynamic.Core/Parser/ExpressionParser.cs#L781

And some unit tests are defined here:
- https://github.com/StefH/System.Linq.Dynamic.Core/blob/8d8ecf9c2340f4518dc377e9fe7a6767dd71e392/src/System.Linq.Dynamic.Core/Parser/ExpressionParser.cs#L781-L726
- https://github.com/StefH/System.Linq.Dynamic.Core/blob/99aacdd95f60bbb859a6799ab1d0d6412d264762/test/System.Linq.Dynamic.Core.Tests/Tokenizer/TextParserTests.cs#L207

**Comment by alexweav** [comment]
@StefH I was able to work around this by running an [ExpressionVisitor](https://docs.microsoft.com/en-us/dotnet/api/system.linq.expressions.expressionvisitor?view=netframework-4.8) on the parsed lambda which simply calls [Regex.Unescape()](https://docs.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regex.unescape?view=netframework-4.8) on all string constants. I wonder if something this simple would solve this issue? It ensures that all escape sequences inside string literals are parsed as escape sequences, not the literal characters. Do you think this is too drastic to apply everywhere?

**Comment by StefH** [comment]
Please make a PullRequest with unit tests or a new sample project.

**Comment by alexweav** [comment]
Test: #325

**Comment by StefH** [comment]
@alexweav and @seregvan Can you please test if version `System.Linq.Dynamic.Core.1.0.20-ci-12219.nupkg` from MyGet solves your issue?

**Comment by StefH** [comment]
@hypetsch and @SolidWhiteSven : you also where involved in string parsing issues, can you also verify if this fix also is in line with your usage?

**Comment by SolidWhiteSven** [comment]
Hey, I've updated to 1.0.20-ci-12230 and all my tests were successful. 
Thanks by the was for keeping this package nice and updated :-)

**Comment by StefH** [comment]
@SolidWhiteSven The version you mention is a different one, you need `System.Linq.Dynamic.Core.1.0.20-ci-12219`.

**Comment by SolidWhiteSven** [comment]
Ah, I see, thought the changes were also included there. 
Retested with version 12219 and it all still works as expected.

**Comment by StefH** [comment]
Closing as solved in PR https://github.com/StefH/System.Linq.Dynamic.Core/pull/326

**Comment by StefH** [comment]
@alexweav --> Can you please test if version System.Linq.Dynamic.Core.1.0.20-ci-12219.nupkg from MyGet solves your issue?

**Comment by rppmartinsCollab** [comment]
> @alexweav --> Can you please test if version System.Linq.Dynamic.Core.1.0.20-ci-12219.nupkg from MyGet solves your issue?

Hi, testing this version, the problem persists.
When doing something like " query.Where("name.contains("\")") ", I´ve got System.Linq.Dynamic.Core.Exceptions.ParseException: 'Syntax error '\''.

Can you help me with this?

**Comment by StefH** [comment]
@rppmartinsCollab To be able to use Contains to check if a string contains a `\`, you need code like:

``` c#
query.Where("name.contains(\"\\\")")
```

1. Escape the `"` with `\"`
2. Escape the `\` with `\\`

Does this work for you?

**Comment by StefH** [comment]
@alexweav, @seregvan and @hypetsch : If you have time, please double check if the updated NuGet (`System.Linq.Dynamic.Core.1.0.20-ci-12219`) works ok for you.

**Comment by rppmartinsCollab** [comment]
> @rppmartinsCollab To be able to use Contains to check if a string contains a `\`, you need code like:
> 
> ```cs
> query.Where("name.contains(\"\\\")")
> ```
> 
> 1. Escape the `"` with `\"`
> 2. Escape the `\` with `\\`
> 
> Does this work for you?

Hey, thanks for the response.

This way I get the error  "Syntax error ' \\ ' " once TextParser does not recognize the character.

**Comment by StefH** [comment]
@rppmartinsCollab Sorry for the confusion, you actually need to escape the `\` twice. So `\\\\`.
For example see https://github.com/StefH/System.Linq.Dynamic.Core/pull/326/files#diff-d7a1783411cc2e7ca08b15984ed427c9R33

**Comment by rppmartinsCollab** [comment]
> @rppmartinsCollab Sorry for the confusion, you actually need to escape the `\` twice. So `\\\\`.
> For example see https://github.com/StefH/System.Linq.Dynamic.Core/pull/326/files#diff-d7a1783411cc2e7ca08b15984ed427c9R33

The problem seems to be in scaping the quote character, I get error in \\\"

**Comment by silarmani** [comment]
Hello guys,

I've just upgraded it to 1.0.21 via nuget and I can confirm that the issue still exists.

It only breaks if the filter is a check for a single backslash

e.g. #1 if I search for \t ["Studyname.Contains(\"\\t\")"], EF produces the correct condition

```
exec sp_executesql N'SELECT [e.Studytype].[ParentID], [e.Studytype].[ChildID], [e.Studytype].[idx], [t].[SYSIDENT], [t].[tdid]
FROM [RV_riskstudytype_STUDIES] AS [e.Studytype]
INNER JOIN (
    SELECT [e0].[SYSIDENT], [e0].[tdid]
    FROM [RV_riskstudy] AS [e0]
    LEFT JOIN [RV_project_PROJECTSTUDIES] AS [jSTUDYPROJECT0] ON [e0].[tdid] = [jSTUDYPROJECT0].[ChildID]
    LEFT JOIN [RV_riskstudytype_STUDIES] AS [jSTUDYTYPE0] ON [e0].[tdid] = [jSTUDYTYPE0].[ChildID]
    WHERE ([e0].[rid] IN (''0'', @__registerUuid_0) AND [e0].[STUDY_STATUS] NOT IN (9, 3)) AND (CHARINDEX(N''\t'', [e0].[STUDYNAME]) > 0)
    ORDER BY [e0].[SYSIDENT], [e0].[tdid]
    OFFSET @__p_1 ROWS FETCH NEXT @__p_2 ROWS ONLY
) AS [t] ON [e.Studytype].[ChildID] = [t].[tdid]
ORDER BY [t].[SYSIDENT], [t].[tdid]',N'@__registerUuid_0 varchar(160),@__p_1 int,@__p_2 int',@__registerUuid_0='3.1.1.risk-register.da7ecd5e8ecc4c91ab3f5fa2a0686346',@__p_1=0,@__p_2=25
```

e.g. #2 if I search for \\ ["Studyname.Contains(\"\\\\\")"], EF produces the correct condition (i.e. text with single backslashes *do not match*)

```
exec sp_executesql N'SELECT [e.Studytype.RiskstudyType].[tdid], [e.Studytype.RiskstudyType].[CODE], [e.Studytype.RiskstudyType].[DESCRIPTION], [e.Studytype.RiskstudyType].[SYSIDENT], [e.Studytype.RiskstudyType].[rid], [e.Studytype.RiskstudyType].[STATUS], [e.Studytype.RiskstudyType].[STUDYTYPEAPPROACH], [e.Studytype.RiskstudyType].[STUDYTYPENAME], [e.Studytype.RiskstudyType].[STUDYTYPEOPTIONS], [e.Studytype.RiskstudyType].[STUDYTYPESTRUCTURE], [e.Studytype.RiskstudyType].[SYSCODE]
FROM (
    SELECT [e].*
    FROM [RV_riskstudy] AS [e]
    LEFT JOIN [RV_project_PROJECTSTUDIES] AS [jSTUDYPROJECT] ON [e].[tdid] = [jSTUDYPROJECT].[ChildID]
    LEFT JOIN [RV_riskstudytype_STUDIES] AS [jSTUDYTYPE] ON [e].[tdid] = [jSTUDYTYPE].[ChildID]
    WHERE ([e].[rid] IN (''0'', @__registerUuid_0) AND [e].[STUDY_STATUS] NOT IN (9, 3)) AND (CHARINDEX(N''\\'', [e].[STUDYNAME]) > 0)
    ORDER BY [e].[SYSIDENT]
    OFFSET @__p_1 ROWS FETCH NEXT @__p_2 ROWS ONLY
) AS [t]
INNER JOIN [RV_riskstudytype_STUDIES] AS [e.Studytype] ON [t].[tdid] = [e.Studytype].[ChildID]
INNER JOIN [RV_riskstudytype] AS [e.Studytype.RiskstudyType] ON [e.Studytype].[ParentID] = [e.Studytype.RiskstudyType].[tdid]
ORDER BY [e.Studytype].[idx]',N'@__registerUuid_0 varchar(160),@__p_1 int,@__p_2 int',@__registerUuid_0='3.1.1.risk-register.da7ecd5e8ecc4c91ab3f5fa2a0686346',@__p_1=0,@__p_2=25
```

e.g. #3 if I search for \ [""Studyname.Contains(\"\\\")""], dynamic core throws exception

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Linq.Dynamic.Core.Exceptions.ParseException: Unterminated string literal
   at System.Linq.Dynamic.Core.Tokenizer.TextParser.NextToken() in C:\Users\azurestef\Documents\Github\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Tokenizer\TextParser.cs:line 361
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseArgumentList() in C:\Users\azurestef\Documents\Github\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 1846
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseMemberAccess(Type type, Expression instance) in C:\Users\azurestef\Documents\Github\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 1633
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParsePrimary() in C:\Users\azurestef\Documents\Github\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 744
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseUnary() in C:\Users\azurestef\Documents\Github\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 733
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseMultiplicative() in C:\Users\azurestef\Documents\Github\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 679
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseAdditive() in C:\Users\azurestef\Documents\Github\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 648
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseShiftOperator() in C:\Users\azurestef\Documents\Github\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 624
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseComparisonOperator() in C:\Users\azurestef\Documents\Github\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 433
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseLogicalAndOrOperator() in C:\Users\azurestef\Documents\Github\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 378
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseIn() in C:\Users\azurestef\Documents\Github\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 298
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseAndOperator() in C:\Users\azurestef\Documents\Github\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 281
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseOrOperator() in C:\Users\azurestef\Documents\Github\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 263
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseLambdaOperator() in C:\Users\azurestef\Documents\Github\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 243
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseNullCoalescingOperator() in C:\Users\azurestef\Documents\Github\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 230
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseConditionalOperator() in C:\Users\azurestef\Documents\Github\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 213
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.Parse(Type resultType, Boolean createParameterCtor) in C:\Users\azurestef\Documents\Github\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 152
   at System.Linq.Dynamic.Core.DynamicExpressionParser.ParseLambda(ParsingConfig parsingConfig, Boolean createParameterCtor, ParameterExpression[] parameters, Type resultType, String expression, Object[] values) in C:\Users\azurestef\Documents\Github\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\DynamicExpressionParser.cs:line 67
   at System.Linq.Dynamic.Core.DynamicQueryableExtensions.Where(IQueryable source, ParsingConfig config, String predicate, Object[] args) in C:\Users\azurestef\Documents\Github\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\DynamicQueryableExtensions.cs:line 2276
   at System.Linq.Dynamic.Core.DynamicQueryableExtensions.Where[TSource](IQueryable`1 source, ParsingConfig config, String predicate, Object[] args) in C:\Users\azurestef\Documents\Github\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\DynamicQueryableExtensions.cs:line 2248
   at System.Linq.Dynamic.Core.DynamicQueryableExtensions.Where[TSource](IQueryable`1 source, String predicate, Object[] args) in C:\Users\azurestef\Documents\Github\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\DynamicQueryableExtensions.cs:line 2254

**Comment by StefH** [comment]
@silarmani Did you use latest from normal NuGet ?
This will not yet work.

Can you please try version System.Linq.Dynamic.Core.1.0.20-ci-12980.nupkg from MyGet ?

**Comment by silarmani** [comment]
@StefH, yes, it does, as long as I escape all backlashes, which makes sense.

For clarity for everyone I am going to repeat all the scenarios I ran before but with this special version and then show the new queries in EF


e.g. #1 if I search for `\t` `["Studyname.Contains(\"\\\\t\")"]`, EF produces the correct condition

```
exec sp_executesql N'SELECT [e].[tdid]
FROM [RV_riskstudy] AS [e]
LEFT JOIN [RV_project_PROJECTSTUDIES] AS [jSTUDYPROJECT] ON [e].[tdid] = [jSTUDYPROJECT].[ChildID]
LEFT JOIN [RV_riskstudytype_STUDIES] AS [jSTUDYTYPE] ON [e].[tdid] = [jSTUDYTYPE].[ChildID]
WHERE ([e].[rid] IN (''0'', @__registerUuid_0) AND [e].[STUDY_STATUS] NOT IN (9, 3)) AND (CHARINDEX(N''\t'', [e].[STUDYNAME]) > 0)
ORDER BY [e].[SYSIDENT], [e].[tdid]
OFFSET @__p_1 ROWS FETCH NEXT @__p_2 ROWS ONLY',N'@__registerUuid_0 varchar(160),@__p_1 int,@__p_2 int',@__registerUuid_0='3.1.1.risk-register.da7ecd5e8ecc4c91ab3f5fa2a0686346',@__p_1=0,@__p_2=25
```
e.g. #2 if I search for `\\` `["Studyname.Contains(\"\\\\\\\\\")"]`, EF produces the correct condition (i.e. text with single backslashes *does not match*)

```
exec sp_executesql N'SELECT [e].[tdid]
FROM [RV_riskstudy] AS [e]
LEFT JOIN [RV_project_PROJECTSTUDIES] AS [jSTUDYPROJECT] ON [e].[tdid] = [jSTUDYPROJECT].[ChildID]
LEFT JOIN [RV_riskstudytype_STUDIES] AS [jSTUDYTYPE] ON [e].[tdid] = [jSTUDYTYPE].[ChildID]
WHERE ([e].[rid] IN (''0'', @__registerUuid_0) AND [e].[STUDY_STATUS] NOT IN (9, 3)) AND (CHARINDEX(N''\\'', [e].[STUDYNAME]) > 0)
ORDER BY [e].[SYSIDENT], [e].[tdid]
OFFSET @__p_1 ROWS FETCH NEXT @__p_2 ROWS ONLY',N'@__registerUuid_0 varchar(160),@__p_1 int,@__p_2 int',@__registerUuid_0='3.1.1.risk-register.da7ecd5e8ecc4c91ab3f5fa2a0686346',@__p_1=0,@__p_2=25
```

e.g. #3 if I search for `\` `["Studyname.Contains(\"\\\\\")"]`, EF produces the correct condition (i.e. text with either single or bouble backslashes matches)

```
exec sp_executesql N'SELECT [e].[tdid]
FROM [RV_riskstudy] AS [e]
LEFT JOIN [RV_project_PROJECTSTUDIES] AS [jSTUDYPROJECT] ON [e].[tdid] = [jSTUDYPROJECT].[ChildID]
LEFT JOIN [RV_riskstudytype_STUDIES] AS [jSTUDYTYPE] ON [e].[tdid] = [jSTUDYTYPE].[ChildID]
WHERE ([e].[rid] IN (''0'', @__registerUuid_0) AND [e].[STUDY_STATUS] NOT IN (9, 3)) AND (CHARINDEX(N''\'', [e].[STUDYNAME]) > 0)
ORDER BY [e].[SYSIDENT], [e].[tdid]
OFFSET @__p_1 ROWS FETCH NEXT @__p_2 ROWS ONLY',N'@__registerUuid_0 varchar(160),@__p_1 int,@__p_2 int',@__registerUuid_0='3.1.1.risk-register.da7ecd5e8ecc4c91ab3f5fa2a0686346',@__p_1=0,@__p_2=25
```

**Comment by silarmani** [comment]
I have also tested permutation using backslashes and double quotes and they all work flawlessly.

Is there a plan for making it available in the next release via NuGet?

**Comment by silarmani** [comment]
e.g. #4 if I search for `\"` `["Studyname.Contains(\"\\\\\\\"\")"]`, EF produces the correct condition

```
exec sp_executesql N'SELECT [e].[tdid]
FROM [RV_riskstudy] AS [e]
LEFT JOIN [RV_project_PROJECTSTUDIES] AS [jSTUDYPROJECT] ON [e].[tdid] = [jSTUDYPROJECT].[ChildID]
LEFT JOIN [RV_riskstudytype_STUDIES] AS [jSTUDYTYPE] ON [e].[tdid] = [jSTUDYTYPE].[ChildID]
WHERE ([e].[rid] IN (''0'', @__registerUuid_0) AND [e].[STUDY_STATUS] NOT IN (9, 3)) AND (CHARINDEX(N''\"'', [e].[STUDYNAME]) > 0)
ORDER BY [e].[SYSIDENT], [e].[tdid]
OFFSET @__p_1 ROWS FETCH NEXT @__p_2 ROWS ONLY',N'@__registerUuid_0 varchar(160),@__p_1 int,@__p_2 int',@__registerUuid_0='3.1.1.risk-register.da7ecd5e8ecc4c91ab3f5fa2a0686346',@__p_1=0,@__p_2=25
```

**Comment by StefH** [comment]
@silarmani Thanks for extended testing!

I want to release this to normal NuGet, however I think I need to change the version from this library to 1.1 because it can be a breaking change.

Also I'm doubting if I should add a new dependency (`<PackageReference Include="Sprache.Signed" Version="2.2.0" />`) or that I should copy these source files into my library ?

**Comment by silarmani** [comment]
Yes, it is breaking change. I would changed it to 1.1.

e.g. the syntax for searching for `\t` changed from ["Studyname.Contains(\"\\t\")"] to ["Studyname.Contains(\"\\\\t\")"]

In regards to adding a new dependency, I don't see it as problem.

I'll stick with the pre-release for now since it doesn't break anything so far.

Thank you!!!
